version: "2.2"
services:
  mongodb:
    image: "mongo"
    container_name: mongo-db
    volumes:
      - data:/data/db
  backend:
    build: ./Backend
    container_name: node-api
    ports:
      - "3001:3001"
    volumes:
      - logs:/app/logs
      - ./Backend:/app
      - /app/node_modules
    depends_on:
      - mongodb
  frontend:
    build: ./Frontend
    container_name: react-ui
    ports:
      - "3000:3000"
    volumes:
      - ./Frontend/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  data:
  logs:
